### ISSUE TITLE
`StatusReceiver` thread is not a daemon

### ISSUE THREAD

**Issue by BryceBeagle** [aotuai/brainframe-python#14]
At one point in time, `StatusReceiver` used to directly subclass `Thread`, and this line was used:
https://github.com/aotuai/brainframe-python/blob/6bfd3b7e88b7bf1025714c41e8e5a30f6aea6413/brainframe/api/status_receiver.py#L34

When we switched to composition instead of inheritance, the `Thread` was accidentally not made a daemon:
https://github.com/aotuai/brainframe-python/blob/6bfd3b7e88b7bf1025714c41e8e5a30f6aea6413/brainframe/api/status_receiver.py#L36-L37

**Comment by velovix** [comment]
Wow Bryce, I think you just about fixed this one!
